language: python
# command to install dependencies
install:
  - python setup.py install
  - pip install -r requirements.txt
# run tests
script: 
    - coverage run -m pytest
after_success:
    - bash <(curl -s https://codecov.io/bash)
